[build]
  publish = "build"  # This should match the folder where your build output is located
  command = "npm run build"  # Command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200